### ISSUE TITLE
S3 returns SignatureDoesNotMatch for list-objects example

### ISSUE THREAD

**Issue by richmarr** [chilts/awssum#33] opened 2012-07-05 07:10 UTC
Running the `list-objects` example with my own S3 details produces two `403` responses, one per request, and both say `SignatureDoesNotMatch`.

Examining the response, it lists the string to sign as: 

```
GET\n\n\nThu, 05 Jul 2012 06:56:30 UTC\n/my-bucket/
```

...but the s3.js `strToSign()` function is determining the string to sign as:

```
GET\n\n\nThu, 05 Jul 2012 06:56:30 UTC\n/my-bucket/?max-keys=4&prefix=c
```

Commenting out this block completely makes the problem go away:

```
/*
// Add all the other parameters onto the strToSign (Note: ignore the fact that the docs call them 'sub-resources',
// - that's just confusing. Also, we need all of the parameters, not the things that they call sub-resources!
if ( options.params.length ) {
    strToSign += _(options.params)
        .chain()
        .sortBy(function(pair) { return pair.name; } )
        .map(function(pair){
            return _.isUndefined(pair.value) ? pair.name : pair.name + '=' + pair.value;
        })
        .reduce(function(memo, pairStr) {
            return memo === '' ? '?' + pairStr : memo + '&' + pairStr;
        }, '')
        .value()
    ;
}*/
```

From an outside perspective this code was written too deliberately and precisely for this to be an oversight, and it seems unlikely AWS would change so rapidly as to break actively-updated API clients... so I'm wondering what this could be. Is it a bizarre configuration issue? Is this another availability-region quirk as I'm using EU_WEST_1? My S3 credentials certainly work _without_ this block, and it's a private bucket so they must be working.

Very confused. I need to get this working so any quick debugging tips would be appreciated even if they're not a full answer.

**Comment by chilts** [comment] 2012-07-13 23:21
Hi Rich,

Sorry to have been delayed replying but I've just come back from holiday.

Firstly, can you let me know which version of AwsSum you are using and which version of node too, thanks?

Can you also paste the exact call to s3.ListObjects() you are doing so that I can see what you're doing and test it with my credentials. I have just recently added some integration tests for this exact thing and it's all working for me.

Cheers,
Andy

**Comment by chilts** [comment] 2012-07-30 06:47
I suspect this is an old version of AwsSum and many of these Signature problems have been fixed. Closing for now but pending re-open if it's still a problem.

**Comment by sputnick** [comment] 2012-08-06 02:58
I'm getting this error too on CreateBucket. I'm using 0.7.0 + Meteor + Node 0.8.5 (started today with a fresh first time setup) OSX 10.8.

I figured out the funny thing that this fails every time I use capital letters in a bucket name but works like a charm if I don't use capital letters. Does that help pin the problem as it seems to be in the latest version?

This an example output when I try to create a bucket with the name "AWSSUMisAWESOME".

  Body: 
   { Error: 
      { Code: 'SignatureDoesNotMatch',
        Message: 'The request signature we calculated does not match the signature you provided. Check your key and signing method.',
        StringToSignBytes: '50 55 54 0a 0a 0a 4d 6f 6e 2c 20 30 36 20 41 75 67 20 32 30 31 32 20 30 32 3a 35 33 3a 35 33 20 55 54 43 0a 2f 61 77 73 73 75 6d 69 73 61 77 65 73 6f 6d 65 2f',
        RequestId: '2BD0D9AC9EC3EBB6',
        HostId: 'F5kYX2x6tfqXtu5k3aRq7ezDeycUw8PNBV9tmUo31VKb8nB1brbzV//eopSp9XFw',
        SignatureProvided: 'JdEFnwtTacxUg0XHftV6Rmq2RFI=',
        StringToSign: 'PUT\n\n\nMon, 06 Aug 2012 02:53:53 UTC\n/awssumisawesome/',

cheers
Eirikur Hrafnsson
Founder GreenQloud

**Comment by chilts** [comment] 2012-08-06 03:01
Hiya,

Thanks for your input.

I wonder if it's something to do with your bucket having some upper case chars. Can you try again for me with all lowercase? If so, I can take a look later on today.

Many thanks,
Andy

**Comment by sputnick** [comment] 2012-08-06 03:07
Not sure that last message was for me or the original bug reporter :)

But to add to my message. Yes creating buckets (with the same name) in lower case works. I have no problem listing buckets myself and they have mixed upper and lower cases. Only when I "write" does it fail.

BTW I want to try to add support for GreenQloud's S3 compatible storage. Usually in libraries it works by simply changing the webservice endpoint to "s.greenqloud.com". Perhaps you could email me with a suggestion on how I should go about doing that (eiki@greenqloud.com). We also support EC2 commands on our truly green cloud but it looks like they haven't been implemented yet in awssum (any plan to?)

cheers
Eiki

EDIT:
Perhaps allowing one to specify the endpoint when creating a S3 object would simply be enough. Or if you add greenqloud.IS region with the endpoint "s.greenqloud.com"...

**Comment by chilts** [comment] 2012-08-06 04:23
That last message was for @sputnick. :) Thanks for the info regarding the fact that lowercase works. That gives me a good start as to why it was failing.

Many thanks,
Andy

**Comment by chilts** [comment] 2012-08-06 05:38
Hiya @sputnick,

Sorry, I didn't realise you'd already mentioned about upper/lowercase bucket names in your original comment - sorry about that. :)

From what I can see, upper case bucket names are not supported in AWS S3 and I don't think AwsSum should support them either. Whilst you can technically create one in US_EAST_1, it'll never work in other regions.

Note: I'm basing this decision on the following two links, the knox one helping quite a lot and setting a precedent:
- http://docs.amazonwebservices.com/AmazonS3/latest/dev/BucketRestrictions.html#bucketnamingrules
- https://github.com/LearnBoost/knox/issues/44

I'd probably stick to lowercase bucket names, if only for the fact that you may want to use them in the future on the web, via either S3 or CloudFront. :)

Many thanks,
Andy

**Closed as completed by chilts** 2012-08-06 05:38 UTC

**Comment by sputnick** [comment] 2012-08-06 20:04
Alright Andy :)

I should have realised that since we built our own Storage Qloud interface in JS :P I remember now that we ascii normalized whatever you named your bucket to comply similar domain naming rules as S3. Consider this a non issue. 

Thanks
Eiki

**Comment by chilts** [comment] 2012-08-07 10:46
Hmm, I wonder if I should throw as soon as someone has an invalid BucketName. The problem is, I'd rather each service did semantic checking such as this since I'd never complete every check and it'd be a futile and worthless exercise. However in this case Amazon S3's problem is the signature.

Sorry, just thinking out loud. Don't worry about this too much. I _may_ try and make the signature with a lowercase bucketname and see if that works ... else I'll just leave it as-is. :)

Thanks again,
Andy
