### ISSUE TITLE
PutBucketLifecycle fails with 'Missing required header for this request: Content-MD5'

### ISSUE THREAD

**Issue by yuvaldrori** [chilts/awssum#122] opened 2012-11-22 19:30 UTC
Same code, after npm update from 0.6.1 to 0.12
https://github.com/yuvaldrori/sfs/blob/master/server/index.js

**Comment by chilts** [comment] 2012-11-24 09:35
I've just done a new release v0.12.1. Would it be possible to upgrade and try again please?

I think you've encountered an error caused by a previous error which I hope to have now fixed. :)

Cheers,
Andy

**Comment by yuvaldrori** [comment] 2012-11-24 13:33
Hi Andy, I updated the module and the PutBucketLifeCycle works again but the PutBucketCors which I do right after, returns with the same error about not having the MD5 header - is it me using the CORS command wrong?
Thanks!!

**Closed as completed** 2012-11-25 08:49 UTC

**Comment by chilts** [comment] 2012-11-25 08:51
Hi Yuval,

Yep, you're right, the PutBucketCors was incorrect since it wasn't adding the Content-MD5 to the request. Sorry about that. Amazing how inconsistent the S3 API is ... some of those PutBucket_Thing_ has the MD5, others the Content-Length, some both some neither! :D

Thanks for your help.

Cheers,
Andy

**Comment by yuvaldrori** [comment] 2012-11-25 08:55
Hi Andy - thank you! I will test it later today to make sure.

**Comment by chilts** [comment] 2012-11-25 09:00
Excellent, thanks. :)

**Comment by yuvaldrori** [comment] 2012-11-25 15:49
Hi again Andy - so the MD5 issue is fixed! but i encountered another problem:
var cors = {'CORSRule':{
  'AllowedOrigin' : '_',
  'AllowedMethod' : 'POST',
  'AllowedMethod' : 'PUT',
  'AllowedMethod' : 'GET',
  'AllowedHeader' : '_',
  'MaxAgeSeconds' : '3000'
}}
If this is my CORS config, it will show only the 'AllowedMethod' : 'GET' in s3, is it possible that somehow only the last one gets passed?

**Comment by yuvaldrori** [comment] 2012-11-25 16:12
Hello again Andy - everything works perfectly! I found how to define multiple nodes reading the data2xml readme...
Thanks for these great modules!!
