### ISSUE TITLE
http redirects..

### ISSUE THREAD

**Issue by tzmartin** [chilts/awssum#28] opened 2012-06-21 03:44 UTC
In testing.. i noticed that 302 redirects are not available for the request object.   It would be nice to have support for redirects.  Any chance you have a pending commit for this? :)

Properties:
-  followRedirect
-  followAllRedirects
-  maxRedirects

Similar to this.. 
https://github.com/mikeal/request/blob/master/main.js#L460

**Comment by chilts** [comment] 2012-06-29 22:49
Hi Terry,

Sorry for not getting back to you earlier. I'm actually on holiday at the moment so just checking in when I can (back home in 2 weeks time). Yes, the S3 redirect thing is definitely something I need to cater for but I haven't yet had it happen to me so it's kinda been left aside.

Many thanks for opening this request and sorry I missed you on irc. Yes, I'm open to a lot of the things you've suggested. If you'd like to send me an email on chilts@appsattic.com we can start chatting since I can check my email more frequently than IRC at the moment. :)

I'll be back on IRC in a couple of weeks time if you'd like to chat there.

**Comment by kosmasgiannis** [comment] 2014-01-28 06:39
Duplicate of #167 ?

**Comment by chilts** [comment] 2016-09-09 03:18
AwsSum is now deprecated in favour of the offical aws-sdk from Amazon. Thanks for opening this originally.

**Closed as completed by chilts** 2016-09-09 03:18 UTC
